enterprise/urls.py
from django.urls import path

from .views import HomeView, ProductDeleteView, ProductUpdateView, SaleView, StockView

app_name = "enterprise"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("product/<int:pk>/update", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete", ProductDeleteView.as_view(), name="product_delete"),
    path("stock", StockView.as_view(), name="stock"),
    path("sale", SaleView.as_view(), name="sale"),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("enterprise.urls")),
]

enterprise/models.py
from django.db import models


class Product(models.Model):
    # Blank = True means that the field is not required
    # Null = True means that the field can be empty in the database
    image = models.ImageField(upload_to="static/images/products", blank=True, null=True)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock_quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        has_stock = (self.stock_quantity - 1) > 0

        if has_stock:
            self.stock_quantity -= 1
            self.save()
            return None

        super().delete(*args, **kwargs)

    # Sort by product quantity, descending
    class Meta:
        ordering = ["-stock_quantity"]


class Sale(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=1)
    quantity = models.IntegerField()
    # This field is not required because it will be calculated, not filled by the user
    total_price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        self.total_price = self.product.price * self.quantity
        super().save(*args, **kwargs)

enterprise/forms.py
from django import forms

from .models import Product, Sale


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        labels = {
            "image": "Imagem",
            "name": "Nome",
            "price": "Preço",
            "stock_quantity": "Quantidade em estoque",
        }
        widgets = {
            "name": forms.TextInput(
                attrs={"placeholder": "Digite o nome do produto..."}
            ),
            "price": forms.NumberInput(
                attrs={"placeholder": "Digite o preço do produto..."}
            ),
            "stock_quantity": forms.NumberInput(
                attrs={"placeholder": "Digite a quantidade em estoque..."}
            ),
        }


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ("product", "quantity")
        labels = {
            "product": "Produto",
            "quantity": "Quantidade",
        }
        widgets = {
            "product": forms.Select(attrs={"placeholder": "Selecione um produto..."}),
            "quantity": forms.NumberInput(
                attrs={
                    "placeholder": "Digite a quantidade que será vendida...",
                    type: "number",
                }
            ),
        }

enterprise/views.py
from django.db.models import Sum
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import ProductForm, SaleForm
from .models import Product, Sale
from .utils import format_currency


class HomeView(ListView):
    model = Product
    template_name = "home.html"
    context_object_name = "products_list"

    def get_enterprise_invoce(self):
        sales_invoice_obj = Sale.objects.aggregate(Sum("total_price"))
        sales_invoice = sales_invoice_obj["total_price__sum"]
        return format_currency(sales_invoice)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sales_invoice"] = self.get_enterprise_invoce()
        return context


class ProductUpdateView(UpdateView):
    model = Product
    template_name = "product_update.html"
    form_class = ProductForm
    success_url = reverse_lazy("enterprise:home")


class ProductDeleteView(DeleteView):
    model = Product
    template_name = "product_delete.html"
    success_url = reverse_lazy("enterprise:home")
    context_object_name = "product"


class StockView(CreateView):
    model = Product
    template_name = "stock.html"
    form_class = ProductForm
    success_url = reverse_lazy("enterprise:home")

    def is_product_existing(self, form):
        product = Product.objects.filter(
            name=form["name"],
            price=form["price"],
        )

        return product.exists()

    def update_product_stock(self, form):
        product = Product.objects.get(
            name=form["name"],
            price=form["price"],
        )

        new_stock_quantity = int(form["stock_quantity"])
        product.stock_quantity += new_stock_quantity
        product.save()

    def form_valid(self, form):
        if self.is_product_existing(self.request.POST):
            self.update_product_stock(self.request.POST)
            return redirect(self.success_url)

        return super().form_valid(form)


class SaleView(CreateView):
    model = Sale
    form_class = SaleForm
    template_name = "sale.html"
    success_url = reverse_lazy("enterprise:home")

    def form_valid(self, form):
        sale = form.save(commit=False)
        product = sale.product

        if sale.quantity > product.stock_quantity:
            return self.form_invalid(form)

        self.update_product_stock_quantity(sale, product)
        return super().form_valid(form)

    def update_product_stock_quantity(self, sale, product):
        product.stock_quantity -= sale.quantity
        product.save()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <script src="https://unpkg.com/phosphor-icons"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="preconnect" href="https://rsms.me/" />
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
  </head>
  <body>
    <header>
      {% include 'partials/_header.html' %}
      <nav>{% include 'partials/_nav.html' %}</nav>
    </header>
    <main>{% block content %}{% endblock content %}</main>
  </body>
</html>

templates/home.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}Início{% endblock title %}

{% block content %}
  <p>Atualmente, o faturamento da empresa é de <span class="highlight">{{ sales_invoice }}</span></p>

  <section class="products">
    {% for product in products_list %}
      <div class="product">
        {% if product.image %}
          <img src="{{ product.image.url }}" alt="{{ product.name }}">
        {% else %}
          <img src="{% static 'images/products/default_product.jpg' %}" alt="{{ product.name }}">
        {% endif %}      

        <div class="product-info">
          <h2>
            <a href="{% url 'enterprise:product_update' product.id %}">
              {{ product.name }}
            </a>
          </h2>
          <p>Há {{ product.stock_quantity }} produto{{ product.stock_quantity|pluralize }} no estoque</p>
        </div>
      </div>
    {% endfor %}  
  </section>
{% endblock %}

templates/partials/_header.html
<h1><a href="{% url 'enterprise:home'%}">Empresa</a></h1>

templates/partials/_nav.html
<ul>
  <li>
    <a href="{% url 'enterprise:home' %}">
      <i class="ph-house"></i>
      Início
    </a>
  </li>
  <li>
    <a href="{% url 'enterprise:stock' %}">
      <i class="ph-package"></i>
      Estoque
    </a>
  </li>
  <li>
    <a href="{% url 'enterprise:sale' %}">
      <i class="ph-currency-dollar"></i>
      Vendas
    </a>
  </li>
</ul>

templates/product_delete.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}Deletar produto{% endblock title %}

{% block content %}
  <h2>Delete produtos do estoque</h2>

  <form method="post">
    {% csrf_token %}
    <p>Tem certeza que deseja deletar o produto "{{ product.name }}"?</p>
    <div class="row">
      <a href="{% url 'enterprise:home' %}">Cancelar</a>
      <button type="submit">Sim</button>
    </div>
  </form>
{% endblock %}

templates/product_update.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}Atualizar produto{% endblock title %}

{% block content %}
  <h2>Atualize produtos do estoque</h2>

  <form method="post">
    {% csrf_token %}
    
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
      </div>
    {% endfor %}

    <div class="row">
      <a href="{% url 'enterprise:product_delete' product.id %}">Deletar</a>
      <button type="submit">Salvar</button>
    </div>
  </form>
{% endblock %}

templates/sale.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}Realizar vendas{% endblock title %}

{% block content %}
  <h2>Realize uma venda</h2>

  <form method="post">
    {% csrf_token %}
    
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
      </div>
    {% endfor %}

    <div class="row">
      <a href="{% url 'enterprise:home' %}">Voltar</a>
      <button type="submit">Salvar</button>
    </div>
  </form>
{% endblock %}

templates/stock.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}Adicionar ao estoque{% endblock title %}

{% block content %}
  <h2>Cadastre produtos no estoque</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
      </div>
    {% endfor %}

    <button type="submit">Adicionar</button>
  </form>
{% endblock %}